### PR TITLE
CRANE Coupling, Lymberopoulos & Economou Validation, and new Plasma Freq. Postprocessor

### PR DESCRIPTION
**Pull request by csdechant**
The following updates for Zapdos include:
- A CRANE coupled version of Zapdos
- Adding CRANE as a submodule
- Adding BC's used from the Lymberopoulos and Economou argon metastable paper
- Adding a Postprocessor that calculates the inverse of the current plasma frequency (so that this value can be used as a time step value)
- Adding a test that includes the CRANE coupling, the new BC's and Postprocessor.

### CODE REVIEW

**Comment by lindsayad** [comment]
This new test, does it run out to a steady-state? If so, then I would say to only execute exodus output on `final`. Can you tighten your solve tolerances? 1e-4 for the relative tolerance is pretty loose. If you're not running to a steady-state, then you should not set the absolute tolerance at all. The looseness of the tolerances is probably why we are getting an exodiff when we run on a different platform, e.g. Mac.

**Comment by csdechant** [comment]
No, the test is not steady-state. The test is the input file base on the Lymberopoulos paper (which can take about 3 - 4 hours to complete), so I pick a earlier point in the simulation to compare. I will commit out the absolute tolerance and tighten the relative tolerance.

**Comment by csdechant** [comment]
I have made the changes to the tolerances for the input file on my local machine. Currently I am running the Lymberopoulos case to completion with these tolerances to double check if the final results changes noticeably when compared to the Lymberopoulos paper (I don't believe they should but wanted to double check). Like I mentioned before, the completed run takes a few hours, so I will upload the new files when the simulation is finish and if there are no noticeably changes.

**Comment by csdechant** [comment]
I was looking at the previous fail and it seemed that only a few debug variables failed. Since this variables are only used to look at the residual for debugging purpose, I am going to commit them out of the test file, if no one objects to that.

**Comment by cticenhour** [comment]
Because there is some system maintenance going on at INL, this is affecting our testing machines. The current intermittent test failures - `stale file handle`- is due to that. We're not sure how long this will last (could be all week). So I'll keep trying to get this stuff submitted periodically until we get it tested.

**Comment by cticenhour** [comment]
Just noticed - make sure you remove the stray output file you left in your test directory that's not in `gold` (`tests/Lymberopoulos_rf_discharge/Lymberopoulos_with_argon_metastables_out.e`)

**Comment by lindsayad** [comment]
@milljm How do I enable automatic testing for @csdechant?

**Comment by cticenhour** [comment]
My understanding is that Corey needs to be added as a member of the @idaholab organization, like me, as a MOOSE User for CIVET to count him as a developer and enable automatic testing.

**Comment by lindsayad** [comment]
Thanks for the contributions @csdechant !!!

**Pull request merged**
