### PR TITLE
Libmesh Assertion Fix

### PR DESCRIPTION
**Pull request by cticenhour**
When building Zapdos in `devel` or `dbg` modes, a LibMesh assertion (see `vector_value.h:118`) is tripped when the `Lymberopoulos_with_argon_metastables_2D_At100mTorr_CourseMesh` test is run, leading to a test failure. A sample assertion violation and error message is shown below:

<details>
  <summary>Click to expand!</summary>
  
```
Stack frames: 35
0: 0   libmesh_devel.0.dylib               0x000000010fb4705d libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1069
1: 1   libmesh_devel.0.dylib               0x000000010fb4261e libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 270
2: 2   libzapdos-devel.0.dylib             0x000000010e0476ee libMesh::boostcopy::enable_if_c<ScalarTraits<double>::value, libMesh::VectorValue<double>&>::type libMesh::VectorValue<double>::operator=<double>(double const&) + 654
3: 3   libzapdos-devel.0.dylib             0x000000010e04a03c SakiyamaSecondaryElectronBC::computeQpResidual() + 780
4: 4   libmoose-devel.0.dylib              0x000000010e69fb84 IntegratedBC::computeResidual() + 228
5: 5   libmoose-devel.0.dylib              0x000000010ebb291f ComputeResidualThread::onBoundary(libMesh::Elem const*, unsigned int, short) + 287
6: 6   libmoose-devel.0.dylib              0x000000010e7f26c6 ThreadedElementLoopBase<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> >::operator()(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, bool) + 310
7: 7   libmoose-devel.0.dylib              0x000000010ebebe3e void libMesh::Threads::parallel_reduce<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, ComputeResidualThread>(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, ComputeResidualThread&) + 110
8: 8   libmoose-devel.0.dylib              0x000000010ebe733e NonlinearSystemBase::computeResidualInternal(std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > const&) + 1150
9: 9   libmoose-devel.0.dylib              0x000000010ebe6c33 NonlinearSystemBase::computeResidualTags(std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > const&) + 307
10: 10  libmoose-devel.0.dylib              0x000000010e8a3da9 FEProblemBase::computeResidualTags(std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > const&) + 1081
11: 11  libmoose-devel.0.dylib              0x000000010e8a3653 FEProblemBase::computeResidualInternal(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > const&) + 115
12: 12  libmoose-devel.0.dylib              0x000000010e8a3268 FEProblemBase::computeResidualSys(libMesh::NonlinearImplicitSystem&, libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&) + 56
13: 13  libmoose-devel.0.dylib              0x000000010ebd5609 ComputeResidualFunctor::residual(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, libMesh::NonlinearImplicitSystem&) + 41
14: 14  libmesh_devel.0.dylib               0x0000000110498f95 libmesh_petsc_snes_residual + 213
15: 15  libpetsc.3.11.dylib                 0x0000000111f09237 SNESComputeFunction + 327
16: 16  libpetsc.3.11.dylib                 0x0000000111f54172 SNESLineSearchApply_BT + 1490
17: 17  libpetsc.3.11.dylib                 0x0000000111f5c0ac SNESLineSearchApply + 284
18: 18  libpetsc.3.11.dylib                 0x0000000111f41ecb SNESSolve_NEWTONLS + 2139
19: 19  libpetsc.3.11.dylib                 0x0000000111f0ff0a SNESSolve + 1770
20: 20  libmesh_devel.0.dylib               0x0000000110498a9a libMesh::PetscNonlinearSolver<double>::solve(libMesh::SparseMatrix<double>&, libMesh::NumericVector<double>&, libMesh::NumericVector<double>&, double, unsigned int) + 954
21: 21  libmesh_devel.0.dylib               0x000000011050bf3b libMesh::NonlinearImplicitSystem::solve() + 283
22: 22  libmoose-devel.0.dylib              0x000000010ecd280f TimeIntegrator::solve() + 31
23: 23  libmoose-devel.0.dylib              0x000000010ebdd3ef NonlinearSystem::solve() + 511
24: 24  libmoose-devel.0.dylib              0x000000010e8a13de FEProblemBase::solve() + 110
25: 25  libmoose-devel.0.dylib              0x000000010e62f066 FEProblemSolve::solve() + 22
26: 26  libmoose-devel.0.dylib              0x000000010e633e3f PicardSolve::solveStep(double, double&, double, double&, bool, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > const&) + 1119
27: 27  libmoose-devel.0.dylib              0x000000010e6328c2 PicardSolve::solve() + 2162
28: 28  libmoose-devel.0.dylib              0x000000010eb07331 TimeStepper::step() + 33
29: 29  libmoose-devel.0.dylib              0x000000010e639708 Transient::takeStep(double) + 152
30: 30  libmoose-devel.0.dylib              0x000000010e638fb8 Transient::execute() + 104
31: 31  libmoose-devel.0.dylib              0x000000010eee2b20 MooseApp::executeExecutioner() + 96
32: 32  libmoose-devel.0.dylib              0x000000010eee3a33 MooseApp::run() + 227
33: 33  zapdos-devel                        0x000000010df96bb0 main + 128
34: 34  libdyld.dylib                       0x00007fff61e663d5 start + 1
[0] /Users/icenct/projects/moose/scripts/../libmesh/installed/include/libmesh/vector_value.h, line 118, compiled nodate at notime
We caught a libMesh error
      Line search: objective function at lambdas = 0.00195312 is Inf or Nan, cutting lambda
Assertion `p == Scalar(0)' failed.
p = 3.27849e-23
Scalar(0) = 0
```
</details>

This assertion is tripped when `_ion_flux` and its derivatives are set to zero in `SakiyamaSecondaryElectronBC` and `SakiyamaEnergySecondaryElectronBC`. The definitions of these variables are generally of the form:
```
_some_scalar_variables * -_grad_potential[_qp] * _normals[_qp]
```
which would have a resulting type of `Real`, rather than `TypeVector<Real>`. A vector `operator=` specialization is evidently catching this, since Zapdos compiles without any type mismatch errors. The assertion is tripped when `_some_scalar_variables = 0` and therefore `_ion_flux = 0`, where the operator specialization translates this to `_ion_flux.zero()`. 

Removing `_normals[_qp]` from the definitions fixes the assertion issue and allows the input file to run successfully in `devel` and `dbg`. Judging from the [article](https://doi.org/10.1088/0022-3727/39/16/018) from which this BC term is pulled, I believe this `_normals[_qp]` is un-needed, as there is a normal vector multiplied in the final return statements in Zapdos. 

@csdechant This change causes an Exodiff with the coarse mesh test, though the relative differences are < 1e-3 (at worst, usually closer to < 1e-5). I refrained from re-golding it for now, since I wanted you to look at the results and see if they check out to you. I'd also like to shorten this test, in order to keep some recent intermittent timeout failures from happening in the MOOSE external apps tests. But first, we need to make sure the results are still good. :-) Check out these changes and let me know how it looks compared to your GEC runs. As far as I can tell, it is still running as expected.

### CODE REVIEW

**Comment by lindsayad** [comment]
Yea the relevant code in `vector_value.h` is:
```c++
  /**
   * Assignment-from-scalar operator.  Used only to zero out vectors.
   */
  template <typename Scalar>
  typename boostcopy::enable_if_c<
    ScalarTraits<Scalar>::value,
    VectorValue &>::type
  operator = (const Scalar & libmesh_dbg_var(p))
  { libmesh_assert_equal_to (p, Scalar(0)); this->zero(); return *this; }
```

**Comment by cticenhour** [comment]
Thanks for adding that Alex - I probably should have in my original explanation over just the relevant line number. 

By the way, did you realize that we don’t have dbg testing enabled on CIVET? I thought we were, but then realized the recipes were only building in dbg and not actually testing. At least on my machine, two of the 1d_dc tests and at least one of the Lymberopoulos tests consistently time out.

**Comment by lindsayad** [comment]
Yes, the timeouts are probably the reason debug test run is not turned on.

**Comment by csdechant** [comment]
Hi, I updated my MOOSE, added this branch to NCSU HPC yesterday and I am currently running the Lymberopoulos 100 mTorr case (which started around 9pm EST yesterday, so should be completed tomorrow 9pm EST). So far, the results match the GEC results when comparing them in Paraview (this is for t=2.124e-6).

**Comment by cticenhour** [comment]
FYI - I am rolling a MOOSE submodule update and replacing some instances of the deprecated `print_perf_log` parameter in this PR as well.

**Comment by csdechant** [comment]
There is a slight difference in the time average electron density between the two branches. The electron density profile near the radial center of the chamber is slightly lower in the new results. Attached are snap shots of the results.
Old results:
Time_Average_Electron_Density_Old
New results:
Time_Average_Electron_Density_New

**Comment by cticenhour** [comment]
I'm having a super hard time telling the difference between these two just by looking at them, so that's a good thing. :-) Does anything else look amiss? If not, then I say we should shorten and then re-gold this test.

**Comment by csdechant** [comment]
No. From what I can see the ions, metastables and the potential variables between the two simulations matched up in ParaView.

**Comment by cticenhour** [comment]
Alright then, if you're good with it, I'll shorten this and re-gold.

**Pull request merged**
