### PR TITLE
Various code standards tweaks

### PR DESCRIPTION
**Pull request by cticenhour**
This PR is a rebase of a grab bag branch I made a few weeks ago and decided to go ahead and push.

This changeset:

- Expands the page for Zapdos code standards, pulling almost entirely from that of MOOSE, since we relied on that standard anyway.
- Contains changes due to running the `hit` tool within MOOSE to format input files to the current MOOSE standard for those. The Schottky emission tests were the worst off here (and the intended focus of this formatting spree), but I found lots of inconsistencies in the input files we have. So, I thought I would just go through all of them to make everything more consistent for new users. 
- Fixes for deprecated MOOSE input parameters related to parsed functions.
- (Finally) Removes the `kernels/simple_diffusion` test that came with the original creation of Zapdos from forking the Stork template repository.

### CODE REVIEW

**Review by csdechant — APPROVED** [review]

**Comment by csdechant** [comment]
The Test deprecated failed because of a CRANE action. In particular, within `AddZapdosReactions::addFunctionRateCoefficient`, the parameter "f_name" needs to be changed to "property_name" due to previous updates to `DerivativeParsedMaterial.C`. This doesn't affect Zapdos currently, since `DerivativeParsedMaterial.C` will check for the "f_name" parameter for now. I approved the reviews, since the conflict is not with Zapdos, but one of the sub-modules. @cticenhour please let me know if you think we should just merge this PR now, or have CRANE updated first?

**Comment by cticenhour** [comment]
I submitted a patch for CRANE [here](https://github.com/lcpp-org/crane/pull/91), which was merged. I forgot to update the submodule though....I will push that up and then we should be good.

**Comment by cticenhour** [comment]
@csdechant wait a little bit before coming back to this - I found a weird issue with the documentation on the code standards page I need to address.

**Comment by cticenhour** [comment]
@csdechant we are good to go for another review here whenever you have time - everything is passing now.

**Review by csdechant — APPROVED** [review]

**Pull request merged**
