### PR TITLE
Secondary electron bcs

### PR DESCRIPTION
**Pull request by keniley1**
This PR addresses several boundary condition-related problems: 

1. Adds multiple ion capabilities to Sakiyama, Lymberopoulos, and Economou BCs (partially addresses issue #49 )
2. Merges @csdechant bug fixes from his debug branch into Sakiyama, Lymberopoulos, and Economou BCs
3. Fixes differing ion flux formulations in Hagelaar BCs; they are now consistent between HagelaarIonAdvectionBC, HagelaarIonDiffusionBC, and SecondaryElectronBC

These changes required re-golding most tests that used these BCs. The changes result in qualitatively identical results, but quantitatively relative differences ranged from 1e-4 to 1e-1 - more than enough to be picked up by exodiff. 

This also paves the way for an upcoming PR with a surface charge material and interface kernel.

### CODE REVIEW

**Comment by csdechant** [comment]
Everything seems good and thanks for adding everything.  Just a note about the "EconomouDielectricBC", you added the option for multiple ions but there is only the one option for the effective potential (_potential_ion). The effective potential is define by the ion collision frequency in the kernels, which should be different for each set of ions. Including multiple effective potentials shouldn't be too hard to add, just the _grad_potential_ion would need be to indexed like the ions. Please correct me if I am wrong or overlooked anything.

**Comment by keniley1** [comment]
Whoops - you are correct. Thanks for the heads up! I wasn't familiar with the use of an effective potential so I didn't think about that. I'll fix that.

**Comment by keniley1** [comment]
Great, but I just realized that there might be an issue with this fix. I now allow for multiple potential_ion variables, but is there any use case for EconomouDielectricBC where there would not be any effective ion potentials, and potential_ion will just be the actual potential of the system? So instead of having 

`ip = 'Arp Ar2p'
potential_ion = 'potential_Arp potential_Ar2p'`

they might have this: 

`ip = 'Arp Ar2p'
potential_ion = potential`

If so, this will cause an indexing issue since right now ip and potential_ion are assumed to have the same length. I can easily throw in an error check to ensure that they're the same length, but if there is a possibility that there's only one potential I'll also need to add another check; something like 

`if (coupledComponents("potential_ion") == 1)
{
    if (getVar("potential_ion", 0)->number() == _var.number())
    {
        [copy _var information into _potential_ion, _potential_ion_id, and _grad_potential_ion vectors]
    }
}`

**Comment by csdechant** [comment]
Maybe, I have seen paper with dielectric boundaries with multiple ions and no effective potential (I don't recall the reason why they exclude it).

**Comment by keniley1** [comment]
Okay, good to know! Just in case I've added a few checks to satisfy both use cases. I think with that this PR is done, unless anyone else has any comments or concerns! 

>  I have seen papers with dielectric boundaries, multiple ions and no effective potential (I don't recall the reason why they exclude it).

Well, in my simulations with multiple ions I don't use effective potentials...maybe that's a mistake! I've never seen much theory justifying one way or the other.

**Comment by csdechant** [comment]
@keniley1, I ran both the 100mTorr and 1 Torr GEC case. The 100mTorr ran fine and gave similar results as before, but the 1 Torr GEC case failed. When trying to use a structured mesh, instead of the standard unstructured mesh, the simulation worked and gave similar results as before. I think this is unrelated to this PR,and I have posted a "Structured vs Unstructured Mesh" topic on the Zapdos forum. Unless anyone else thinks this meshing issue has anything to do with the PR, I will merge the PR later today.

**Comment by csdechant** [comment]
@keniley1, I ran both the 100mTorr and 1 Torr GEC case. The 100mTorr ran fine and gave similar results as before, but the 1 Torr GEC case failed. I rearranged some of the real term in the EconomouDielectricBC (link here: https://github.com/csdechant/zapdos/blob/structured/src/bcs/EconomouDielectricBC_Rearranged.C. This seem to help with the residual norm, but the run still failed.

When trying to use a structured mesh, instead of the standard unstructured mesh, the simulation worked and gave similar results as before. I think this is unrelated to this PR,and I have posted a "Structured vs Unstructured Mesh" topic on the Zapdos forum. Unless anyone else thinks this meshing issue has anything to do with the PR, I will merge the PR later today.

**Comment by keniley1** [comment]
I actually think I found a very small bug in the Hagelaar secondary electron emission BC that I'd like to fix before merging, so let me figure that out first. 

(And obviously if your issue _does_ happen to be relevant to something in this PR we should fix that as well!)

**Comment by keniley1** [comment]
I pushed the update I was talking about, but now we're getting a libmesh build error...I have no idea what could possibly cause that.

**Comment by cticenhour** [comment]
I invalidated (reset) the test recipe in order to see if this was just a fluke. The libmesh script was thinking that the test compiler wasn't able to compile executables, which is unrelated to anything you're doing here. If it happens again, I'll take a closer look.

**Comment by keniley1** [comment]
Awesome, thanks @cticenhour! Looks like that fixed it. 

This PR is finished as far as I'm concerned.

**Pull request merged**
