### PR TITLE
AD Zapdos

### PR DESCRIPTION
**Pull request by cticenhour**
At long last (and a bunch of rebasing), here it is - an AD-ified version of Zapdos! Marking this as WIP for now to stop CIVET testing, since there are still a bunch of tests to fixup, and some more Materials conversion work to be done before it's ready for review.

### CODE REVIEW

**Comment by cticenhour** [comment]
@csdechant @lindsayad @keniley1 - requesting all three of you for review on this one since it's a big one... 
Would adding some sort of checklist help on working through the review for this? 

@csdechant one thing in particular I'd like you to look at: I needed to re-gold both of the accelerations tests (as I thought I might, in our previous conversation), so I'd like you to look at the new versions and make sure they fit with what you're expecting here, since I have less experience running them. Notes on the diffs experienced in these for your reference can be seen in the commit messages for 29b0955 and cddfb96

**Comment by csdechant** [comment]
Thanks Casey for all this work. If the most part, everything looks good to me. I do have a few comments and questions:
- I ran some of the MMS tests from my 'paper-update' branch and they passed (note that the gold files for those tests are copies of the Non-AD versions).
- While running the tests on my laptop, only "DriftDiffusionAction.WaterPlasma" failed due to ~ 5.4e-05 diff for two aux-variables (Current_OHm & tot_flux_OHm). I am use Ubuntu 20.04 LTS.
- While making the MMS tests in the 'paper-update' branch, I found that there was an error for the non-AD LymberopoulosIonBC (there was a missing negative sign in one of the OffDiagJacobian). This BC was used in the accelerations tests and the RF plasma tests. I am assuming that this is one of the reasons for the differences between the AD and non-AD gold files (i.e. the error was small enough that it was not noticeable for the output files in Paraview, but big enough for the testing system).
- Why are the "User" kernels being deleted? I am assuming it's because no one uses them and there is no test for them.
- Why keep the electron/energy versions of kernels (e.g. CoeffDiffusionElectrons)? With AD, there should be no difference in the kernels, since the residuals are the same with different material properties.
- Why keep the "AD" in "ADPotentialSurfaceCharge"?
- In the Gas material files, the _kiz and _kex variables do not have a defined AD derivative. Why is that? Also, I don't think these properties are used in any test, since the plasma-water interface tests use Townsend coefficients.

**Comment by cticenhour** [comment]
Thanks for the comments - here are my responses.

>     * I ran some of the MMS tests from my 'paper-update' branch and they passed (note that the gold files for those tests are copies of the Non-AD versions).

Awesome - thanks for checking! 

>     * While running the tests on my laptop, only "DriftDiffusionAction.WaterPlasma" failed due to ~ 5.4e-05 diff for two aux-variables (Current_OHm & tot_flux_OHm). I am use Ubuntu 20.04 LTS.

I have noticed in my other work that there are some differences between Big Sur and previous MacOS versions that are producing these larger diffs for the same code. Doesn't happen all the time, but I've definitely seen it occur. The testing system uses CentOS, so there's likely yet another platform difference between it and Ubuntu 20.04 as well. I'll tweak the cmp file to compensate, since I think that diff is still acceptably small. 

>     * While making the MMS tests in the 'paper-update' branch, I found that there was an error for the non-AD LymberopoulosIonBC (there was a missing negative sign in one of the OffDiagJacobian). This BC was used in the accelerations tests and the RF plasma tests. I am assuming that this is one of the reasons for the differences between the AD and non-AD gold files (i.e. the error was small enough that it was not noticeable for the output files in Paraview, but big enough for the testing system).

If that is the case - would you prefer I re-gold the files that use this BC? 

>     * Why are the "User" kernels being deleted? I am assuming it's because no one uses them and there is no test for them.

They were un-used and un-tested, and they were also just duplicates of capability elsewhere (same names, just lacking "User" in them). I kept the duplicates. I think they were from an era when MOOSE didn't know how to interpret user-defined alternatives for certain parameters (e.g., putting down a number for a variable parameter during testing, etc), so you had to make one with more generic parameters to perform some de-coupled testing. 
 
>     * Why keep the electron/energy versions of kernels (e.g. CoeffDiffusionElectrons)? With AD, there should be no difference in the kernels, since the residuals are the same with different material properties.

I kept them around temporarily because I wasn't sure if they were still being used in your in-progress work. My attempt to reduce possible rebase issues. I noted down a few that need to be removed due to identical Residual contributions. So I can do that in this PR if you'd like, rather than one in the future. 

>     * Why keep the "AD" in "ADPotentialSurfaceCharge"?

Purely an oversight! Thanks for the catch :D 

>     * In the Gas material files, the _kiz and _kex variables do not have a defined AD derivative. Why is that? Also, I don't think these properties are used in any test, since the plasma-water interface tests use Townsend coefficients.

Because `TemVolts` in the definitions is an AD property itself, which is calculated based on AD variables. So the derivatives of these members are handled by the AD system and do not need to be explicitly defined. Those values that depend on interpolations or do not include AD objects in their calculation should be defined using the `derivatives()` function.

**Comment by cticenhour** [comment]
An overall comment related to code coverage issues that you alluded to - we really should run a formal code coverage check at some point and shore up where we can because we know there are gaps. 

Further, a complication exists for all of those syntax check tests we have - those don't feed into the determination of what code is tested, since they don't technically run. We just know that those files *could* run at least past the initial condition and might still error out.

**Comment by csdechant** [comment]
Thanks for the answers.
- Yes, re-gold the files that use the LymberopoulosIonBC is probably for the best.
- I have been using ADCoeffDiffusion, ADEFieldAdvection, etc. for all my charged particles, so it shouldn't cause an issue.
- I must of over looked TemVolts being an AD property. Thanks for the clarification. 

Can you elaborate on the formal code coverage check? Do you mean to test each part of Zapdos separately, instead of having test with multiple source of error?  That is what I hope to start that with the MMS test folder, since each test is for one BC or series of kernels (e.g. one is diffusion only, one is diffusion/advection, one is diffusion/advection/ChargeSource, etc.).

**Comment by cticenhour** [comment]
> Can you elaborate on the formal code coverage check? Do you mean to test each part of Zapdos separately, instead of having test with multiple source of error? That is what I hope to start with the MMS tests, since each test is for one BC or series of kernels (e.g. one is diffusion only, one is diffusion/advection, one is diffusion/advection/ChargeSource, etc.).

Not exactly - I meant making sure the tests we have properly test all of the lines of the implemented code. Having more complicated tests is fine, as long as it properly tests what it needs to test. An excellent thing about your MMS work is that it'll likely help us achieve better coverage on instances in the code that the large tests might not hit, since they're problem-driven! 

Formal "code coverage" is usually tested via a tool. The MOOSE Framework uses `lcov` - see an old output of that test recipe [here](https://civet.inl.gov/job/647377/). At that time (~5 months ago), MOOSE as a whole had about 81.6% coverage (with respect to lines, so 81.6% of all lines of code in MOOSE were hit by a test). The rule of thumbs of what is "good" is different for each project, but MOOSE tries to stay above 80%. Note that line coverage can differ from function coverage - MOOSE hit about 69.3% of all functions in the framework at that time. Some people prefer to judge by lines, some by functions.

Hope that helps!

FYI - The last two commits I pushed had the following changes

* Re-golded tests that use `LymberopoulosIonBC` (that had not been re-golded already, like the accelerations tests) and removed any cmp files associated with those.
* Removed `DriftDiffusionEnergy` and `DriftDiffusionElectrons` in favor of `DriftDiffusion`
* Removed `EFieldAdvectionEnergy` and `EFieldAdvectionElectrons` in favor of `EFieldAdvection` (which made a small change in `DriftDiffusionAction` as well)
* Removed `CoeffDiffusionEnergy` and `CoeffDiffusionElectrons` in favor of `CoeffDiffusion`
* Fixed up all tests affected by these changes
* Adjusted the cmp for the WaterPlasma test

**Comment by cticenhour** [comment]
Ha! An example of the platform differences on Mac I mentioned earlier - https://civet.inl.gov/job/752181/

Regolded and removed the cmp for those failures, yet its different enough to trigger on the previous version of MacOS that the test box uses.....such a headache.

**Comment by cticenhour** [comment]
@csdechant Alright, we're back to green testing. Did you have any other comments or things you'd like me to change?

**Comment by csdechant** [comment]
Yes, just two more comments. 
- The `crane_action.crane_rate_coefficients` failed on my laptop due to a diff in the variable `emDeBug`. If I remember correctly, that variable was mainly for looking a the residual of the electrons for debugging purposes on an older problem and the variable might of carried over to the test file. Since that was the only thing the was different, commenting out or deleting the "DeBug" variables should be fine (if everyone else is ok with that).
- This is more of a minor comment, the `PotentialSurfaceCharge` files are edited correctly, but the file names still have AD (i.e `ADPotentialSurfaceCharge.C` & `ADPotentialSurfaceCharge.h`).

**Comment by cticenhour** [comment]
I was going to ask you about the debug variables yesterday and forgot about them - thanks for the reminder. If their only use was for debugging during development, but are no longer required, the file should be regolded without the variables in it. 

Oops! Thanks for the catch on the filename

**Comment by cticenhour** [comment]
@cedechant - I think we might be ready for a formal GitHub review?

@lindsayad @keniley1 I also want to give you another opportunity to chime in.

**Review by lindsayad — APPROVED** [review]
This looks good to me. Impressive work @cticenhour . This is an awesome cleanup!

**Review by csdechant — APPROVED** [review]
Everything looks good to me!

**Review by keniley1 — APPROVED** [review]

**Comment by keniley1** [comment]
Agreed -- awesome work @cticenhour ! Thanks for taking the time to do this.

**Comment by cticenhour** [comment]
Thanks everyone!

**Pull request merged**
