### PR TITLE
Add species

### PR DESCRIPTION
**Pull request by keniley1**
Adds the capability to include multiple heavy species from the input file. (Still only works with pure argon at atmospheric pressure, however.)

### CODE REVIEW

**Comment by lindsayad** [comment]
@keniley1 Sorry I forgot about this. Can you jog my memory on the failing test issues? It looks like you should be able to fix the failing test by updating the custom comparison file and/or just loosing the overall comparison tolerance

**Comment by keniley1** [comment]
@lindsayad No worries, I also forgot about it...
Yeah, the difference is essentially just a few element variables. If I change the tolerances in the .cmp file to 1e-4 it works fine. The issue is more that the differences are coming close to being significant...1e-4 is small, but I would expect operating system differences to be smaller than that. 

What is giving me the most pause is that on my Mac, the failure is with the original 1d_dc test (which I specifically avoided modifying). When I first started with Zapdos all of the tests passed, so something has changed in the last ~6 months with my own computer. 

Anyway, if changing the .cmp file to have a tolerance of 1e-4 is acceptable to you, I can go ahead and do that. Otherwise I'll try to figure out the root of this issue.

**Comment by lindsayad** [comment]
That's acceptable to me, especially if they are auxiliary variables

**Comment by keniley1** [comment]
Everything should be working now!

**Comment by lindsayad** [comment]
Thanks @keniley1!

**Pull request merged**
