### PR TITLE
Update moose submodule and fixup deprecated code/parameters

### LINKED ISSUE #123: Deprecation errors
Scheduled deprecated testing is back (nightly): https://civet.inl.gov/job/1023673/

It's worth trying to fix these when possible.

Ping @cticenhour

### PR DESCRIPTION
**Pull request by cticenhour**
This is a replacement for #122 due to CIVET issues. 

Closes #123

### CODE REVIEW

**Comment by cticenhour** [comment]
@milljm @loganharbour I am *still* seeing these JSON errors, even when creating an entirely new PR. Any idea what might be going on here?

**Comment by loganharbour** [comment]
This is the continuing cache issue we've always had.

**Comment by cticenhour** [comment]
Right. It just doesn't make sense to me to continue when creating a new PR, which I thought would clean out cache. On invalidation number 14 for this set of changes, give or take.

**Comment by cticenhour** [comment]
@csdechant Mac target is broken during conda initialization, but tests fine on my local machine. We're hitting a serious caching issue over and over that I think our new conda system will fix. In this meantime, can you give this a formal review? I may go ahead and push this into devel to get a submodule update and (maybe) force a cache clean out.

**Review by csdechant — APPROVED** [review]
I checkout out the branch on my Ubuntu, and all the test pass. I should note that when looking over the input files in the `problem` directory, they still have some old formatting that causes errors when trying to run. I can update these files now with this PR, or create a separate PR for this issue.

**Comment by cticenhour** [comment]
Thanks! I've cleaned up the problem directory on another branch, so I would make an issue and I can take care of it.

**Pull request merged**
